name: resala
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  get:
  get_it:
  get_storage:
  webview_flutter: ^3.0.4

  flutter_bloc:
  connectivity_plus:
  dartz:
  dio: ^5.0.3
  flutter_svg:
  animated_bottom_navigation_bar:
  carousel_slider:
  cached_network_image:
  syncfusion_flutter_datepicker: '20.4.43'
  url_launcher:






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed:
  freezed_annotation:
  build_runner:
  json_serializable:

  flutter_launcher_icons:
  #flutter pub run flutter_launcher_icons:main

  flutter_native_splash:
  #flutter pub run flutter_native_splash:create

  change_app_package_name:
  #flutter pub run change_app_package_name:main com.new.package.name

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/Resala Logo 1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher/Resala Logo 1.png"


flutter_native_splash:
  background_image: "assets/launcher/Resala Logo 1.png"
  fullscreen: false
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/launcher/
    - assets/fonts/
    - assets/image/

  fonts:
  - family: BalooBhaijaan2
    fonts:
      - asset: assets/fonts/BalooBhaijaan2-Medium.ttf
        weight: 500
      - asset: assets/fonts/BalooBhaijaan2-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/BalooBhaijaan2-Regular.ttf
        weight: 400
      - asset: assets/fonts/BalooBhaijaan2-Bold.ttf
        weight: 700
      - asset: assets/fonts/BalooBhaijaan2-SemiBold.ttf
        weight: 600
